__author__ = 'Reijer'

def get_frequency_dict(sequence):
    freq = {}
    for x in sequence:
        freq[x] = freq.get(x,0) + 1
    return freq

# def isdna(s):
#     DNA = ["a", "t", "c", "g"]
#     if s in DNA:
#         return
#     else:
#         print "This is not a DNA string."

def test():
    s1 = "CGGGGTGAGGTCGACACGAATCTCGCACCGGTAAAGCTAAAGGTTACGGACTTGTCGGAACTTGTGTATGTTCAATGTGTACCGAACTGGAGCTCTGCCTCCTACCGAACAAGATCTCGTTTCTTCGCTGGTGGTGCCTTGGTCGGGCGGACGAATGTGTCTTAACATTACTGGTTAGAGACTGCTTGGCAGTGTGGACACTCCGTTCCCTTTACTCCTGTAGAACGCGCCTTCAGTGGACGCGTTTATAGGGCGTCATAAAATTTGCATGATTATATCAACTTAAAGCCGTATATCCAGACCTTCCTGTGCGACACAGATGAGGAGGCTATGCGATCTTGACTCGGCCTATAGCATGTACCTAGATCCTTCCGTAATTATCCAGGCGTCCCCACCTGTACACTAGCAGACGAAATCTGCCGACACAAGCGTTCGATTGGCAACCATTTTCACGTGGTCCCTGGCTAAATGCGCTGAGGTACCATTTCGATGCAAGGGCCTTAAAACGGCGATGGTGTAGGAATCTGAAAAACGGAGTAGACCGCAACGGGATGACCTCCTCGAGGCACACGGTAATGTCCTGTAGAACGGGGCCGGAGATACGGCCTGGAGAGATTACAAACGATGCTCACTACCAGTCGTAAGTGACTTTAATGAGTGTTGCGCCGTATACTTCCATGATTGCAACCAACGTCCCGACCGCCCAGCGGTCAGAAATGTGAAATCACCATTATGAGATATTTGACATATGATCTTTGTTATTAGTGAACCCCCAACGTGTGAGGGTACACATCTAGTAATGAACTCAGCCACCCTCATCGATCATCCAAAGGTAG"
    s = "CCCTGGCTCCATTGCCACGATTAATTGAATTTAAAATCGCTCCTGTGGACTGTAGCTCCCGCCCCCATAATCTAAATAATGGGCCCCGCTTGATTTGGGCTTTGTATGATAGCCCGAAACTTTGTAATGAGTTATCGCTATTACTTCTGTAAATAGTCAAGCTTTGTAAGGTGGGACGCGGTGAACTTCTATTCGCCAGGGCGTGTGGGGGCAAGCTAGTTTTCTCAGCGTGAGTTCCTGGAGTAGGTTTTAATGTACCAGGCCATGGGTAACACAGAAGCATCCTTTTAGATGCTTCGGTACCAGATGCAACGGTTCACGTTATCGTTACAATTCTACCAAGTAAGCTGCTCCGCGTACGTTTACGGACGGTAGGCCCATCTGCACATCTATAGAAGACGTCAACATGAAACATCTATTGCCACCGAAATATGTGGTTACGTGATCGGACTGGGGTTCTGTATACAATCGCGTGCATTCTAAGTATATTTGCTGGTAGAGGTTCGCCATGCGCCAACCAGGGCAGGAAGCGGGCGTGCGAAACCGGTACTTTTTGCCTATTGTACCCTATACTAGGGGGAGATACATTATTAGACCACCTCACTAAGGTCGACACTGTTACAGTCTGATGCTTGGCTATATCACTCTCACGCCACCTTAGGGTTTCTAAGGGCATATTCCTTTACCGCACACTCTATGAACGCTCCGAACAAAATGGACCTAGGTTCGCGGCTCGTCGTCAATGATCCCCTTCCAAAAGCAGTTGGAGGTAGTATGGGGGTAAACTTCCATTAACATATCGTAACACTAAACCAAATGTAGCGACCTTTGGTTCGACGAAATGTCTGTGGCACGTAATGCTTATCGAACTTTGATGTCTCAGTTCAAATCACGTTCACAGACTGTGGTGGTGGTCAAAACATCCTGTGCTTAGACGTAAGGGATGCATCTCCCTCGAGTGCCAGAGC"
    # isdna(s)
    freq = get_frequency_dict(s)
    nb = ("A", "C", "G", "T")
    for i in nb:
        print i,
    print freq
    for i in nb:
        print freq[i],





if __name__ == '__main__':
    test()