__author__ = 'Reijer'

import time

amino ={
"UUU":"F", "CUU":"L", "AUU":"I", "GUU":"V",
"UUC":"F", "CUC":"L", "AUC":"I", "GUC":"V",
"UUA":"L", "CUA":"L", "AUA":"I", "GUA":"V",
"UUG":"L", "CUG":"L", "AUG":"M", "GUG":"V",
"UCU":"S", "CCU":"P", "ACU":"T", "GCU":"A",
"UCC":"S", "CCC":"P", "ACC":"T", "GCC":"A",
"UCA":"S", "CCA":"P", "ACA":"T", "GCA":"A",
"UCG":"S", "CCG":"P", "ACG":"T", "GCG":"A",
"UAU":"Y", "CAU":"H", "AAU":"N", "GAU":"D",
"UAC":"Y", "CAC":"H", "AAC":"N", "GAC":"D",
"UAA":"Stop", "CAA":"Q", "AAA":"K", "GAA":"E",
"UAG":"Stop", "CAG":"Q", "AAG":"K", "GAG":"E",
"UGU":"C", "CGU":"R", "AGU":"S", "GGU":"G",
"UGC":"C", "CGC":"R", "AGC":"S", "GGC":"G",
"UGA":"Stop", "CGA":"R", "AGA":"R", "GGA":"G",
"UGG":"W", "CGG":"R", "AGG":"R", "GGG":"G"
}

def get_frequency_dict(sequence):
    freq = {}
    for x in sequence:
        freq[x] = freq.get(x,0) + 1
    return freq

def Pmrna(protein):
    teller = 1
    freqamino = get_frequency_dict(amino.values())
    for i in protein:
        teller *= (freqamino.get(i) % 1000000)
    return (teller * freqamino.get("Stop") % 1000000)

def main():
    start_time = time.time()
    s = "MVKWNHHSQQGDQEFMIWDFPIAMKQHNVPFIYVCQTTIWNYPHRCRNKTTYKMQHSPFTDAGFYDGWQLSLGNEKMWWSKCDPLVFKFTNVRSNFYSEAKMCCWELQCLAKDCCFVQFKFIFWRTRQEEYLVSLPSHLLHICQHKFYAFHTESGRFSPQWDIKVDTQQITGHLPMVQQQWLIVSWAPSCFGCCWQNRGDEGEPDFTFPIETQTHFMYWGRMWVKLTYLMPYHCDSECALMMGTFNASIKKHEPNMCGACDDSVRNFLKCSDCNGASNCNDFIDSAPGKGEQNRKGALRECLLCHQNKIDLDFGGLNGLSVSLLWISAHPWRWRFCHCLHQDHSIEAAEAHLWSMQYQCFAWWPCMICQHCEYFTMFTHLANNCHEKSDESQDDKRFGEPPAVDDPCSGPCTLVIQAVGDTFANKAGHGGHAEQQTGLNLSHAWHWGRLIVQWCYLQAKVTKQVVHWGQNPPGCANFYYMKKEGFKDAMPDAKRICLVGCFIWVPGDNDNDRIDQRMKIIGPCPVLWHKIVAWGWVTAMNNQLDAYFWISENIGKACDTQGFRDHIINFKYLDRRYTCKVSKCWEQREPFTPVWVEEIERTCFRLFLLMPRQVTIFNCLSHLLTVCFYLGSIETIYCRKYDGMEFNLTGICNFIGIVTCREFAWDVQPVDNWENHCQHQMCMTGWESNTDTQNVQAWCREFAIWVIKGSWSPDCFKLQTHGCHTPFPATLVAMYLCNMWCRWAIAKEGRSKDPVFHAIHSQKAVGASIQNCTASPKYSCRQWETKWEVNTKHTSQYFYDCNEPMHEPSKSMHMFADGEDDCQSDGHQNSNPNAHEWEWLFGGGEEAIIKQATFTHARIMHSQLKKGMRPQCNFFSPHPTCTMEVMEMWVIPIIVCIEQGANRQWISWKDKELPCWDVQFNSWRHMLHRDLNWHNWYTYPWAEGNKRIIQQAPIWTRHDPKFFPQMKMRYHQLNYLQQREFNWWNEAYGCFFVGSLGY"
    print Pmrna(s)
    print("--- %s seconds ---" % (time.time() - start_time))

if __name__ == '__main__':
    main()