__author__ = 'Reijer'

def motif(s, t):
    """takes string s and search string t, returns list of hits 0-based"""
    return [n for n in xrange(len(s)) if s.find(t, n) == n]

def test():
    # s = "GATATATGCATATACTT"
    # t = "A"
    s = "CGTCTCCGTCAGTCTTTATTCTTTATTCTCTTTATACTTCTTTATAAAGTCTTTATGTCTTTATATCTTTATGCTCTTTATGATCTTTATGGCCTCTTTATTCTTTATTCTTTATTCTTTATAGCGTCCTCTTTATATCTTTATATCTTTATTTTTTCTTTATTCTTTATTCTTTATTCTTTATTCTTTATTCTTTATGGTCTTTATATGAAAGATCTTTATTCTTTATTGTATTCTTTATACAATGATCTTTATTACTCCATAGTTCCTCTTTATGCTCTTTATTAACTGTTGCCTCTTTATATCTTTATTTGTCTTTATCTCTTTATTCTTTATACTCTTTATTCTTTATCTCTTTATTCTTTATTCTTTATGTCTTTATCCTTCTTTATATCTTTATATCTTTATTATCTTTATAGCTAGTTTCTTTATTTTTCTTTATTTCTTTATGAATCTTTATTGTCTATTGTTCTTTATTTCTTTATCCTATCTTTATTCTTTATCTCTTTATAAAAGGTCTTTATAGTCTTTATGTCTTTATTCGCGTCTTTATTCTTTATTCTTTATCCTCTTTATTCTTTATCTATTCTTTATGAGCGGTTGATTATCTTTCTTTATCAGGCAAGACGCATCTTTATTTGCGTTTTCTTTATTCACTCTTTATTCTCTTTATATCTTTATCTCTTTATCTGGCTTTCTTTATTCTTTATATCTTTATTTCTTTATGGTCTTTATGCTGTCTTTATTCTTTATAGGAGTCTTTATTCTTTATCCTATATCTTTATAGTCTTTATATCTTTAT"
    t = "TCTTTATTC"
    m = motif(s, t)
    for i in m:
        print i+1,               #transforms to 1 based numbering


if __name__ == '__main__':
    test()