__author__ = 'Reijer'

import time

pointm = {"A": "G", "G": "A", "C": "T", "T": "C"}

def r(s1, s2):
    transition = 0
    transversion = 0
    for i in range(len(s1)):
        if s1[i] != s2[i] and s1[i] == pointm.get(s2[i]):
            transition += 1.0
        elif s1[i] != s2[i] and s1[i] != pointm.get(s2[i]):
            transversion += 1.0
    return transition/transversion

def main():
    start_time = time.time()
    # s1 = "GCAACGCACAACGAAAACCCTTAGGGACTGGATTATTTCGTGATCGTTGTAGTTATTGGAAGTACGGGCATCAACCCAGTT"
    # s2 = "TTATCTGACAAAGAAAGCCGTCAACGGCTGGATAATTTCGCGATCGTGCTGGTTACTGGCGGTACGAGTGTTCCTTTGGGT"
    s1 = "CCGGACGTGAGCGAGACATCTCAAGTCCGCGCATCCAGTTGTTACATGCTAACCCCTCCGCTTTGGTCCAATGTGTTTCGTTCGTCTTTAAAAGAACTTATTGATCTATACAAAGGTTTACTACTGTGGGGCATGCCATTTGCGTGGAGGAAACAAAGCCAATATCATCATGCCGTTGCAAACGATGCCCGGGCTGGCGAGAGAAAATGCATGCTGAAAACTGGAGACCACGCCGCTTCAAAACACAATGCATAAACGATATCGGTGCCTAATAAAGCCTTGTCCCATTCTTGGTATAGAAGTATCTAGGTTGAGTAAACGAATCCACTATTGTTCGGATCTCTTCCTATCTTGCGCAATACAATGAAGTTCCTTTACTTAGCGATAGTTGGGTAGTTGTCTGTACCTTATTGCAAATGTATTCAGCTAGCTGACAGTCAACGAAACTCTCGAACATTAGGGCCCAGGGTAAAAATTCATACGAGACGGCCAAACTATATATCTCCTAAAAAGTGAAAGTGCGATGCCAAGGCCTTGAATCAGTTGCTATATGTATAACTCACTAGCAGTCTCGATAAATGACTGGGGTGGTTAGTTAGTTTAAAAAGCTACCGAGTTAGACGTGCTATTCGACTTTCATGCAAAGGCGGATCTGAGCATGTCTTGGCCAAGTTAATAATGCCGCTGAAACCGCCACATTCCTCGGGGCTCAGGGCATGGGATAGGCGGTCCTATAAAAAAATCGCGGGCTGAAAATACGAACAATTCTTGCAGAATTGACGAACTTTCAGACAAACCTAATGTATGTGAACATCTCTTCGTGAGCTCTTGTCTCTTTATGATGTCAGATCAGAATGTTTGTTGTTT"
    s2 = "CTGAAAGTAACTGGAACTTCTCAAGTCCGCGCCTCCAGTTGTCACGTGCAATTCTCCCTGTTTTAGCCGGATGGCATTTGCTCGTCTTTAGAAGAGTCCATTGGTTCATACAAAGCCTTCCTACTCTGAGGCATGCCAGTTGCGTGGGGGAGGTAAAGCTTACATTGTTCGACCGTCGTAGCTAATGTCTAGCCCGCCAGGAAAAATTGCATGCGAAAAGTTGGGAACCACTCCGCTCTAGAACGCGATGTAAAGACGATATCAGGGATAAGTCAAGCCTTGTTTTAGTCTTGCTATGGACGTACCTCGGTCGGGTAGAAGAATCCACACACAACCGGATCTCCTACTATCTTGGGTGTGTCAACAAAGTCCCTTTACCTAGCAATGGTTTGGTGGGTACCTGTACCTGAAGGCAAAGATAGTCGACTTGCCGTCAGCTAACGAAGATCTCAAACACTACGATTCAGGGCAAAAAGTCGCACGGGAGGACCAAATCGTATATCTCTTGAAGAATGAAAGTGCGATACCGAAGCCTCGAGTGAGCTGTCACGTCTGTAAACGACTAGCCATTCTAATAAATGGCCGAGTTGGTTATTTGACCTAAAAAGCTGTTAAATGGGGCGTGCTATTCGACTATCGCCCAGAGGCAGATCTATGCGGGTTTCGACCAGGACAATGGCACCGCTGAGACCGCCACATGTTTCGGTGCTCTGGGCATGGGGTACGCGGGCCTAAGAAAGAATCACGCGTTGAAAACATGAATAACTCTTGCGGAGTAGACGAACTTCCAGTCGAACCCAGCGCGCGAGGATATCCCCCTGCGGGTTCATATTCTGCCATAGTGCCGGATCATAGTGTTTGCTGTTA"
    print r(s1, s2)
    print("--- %s seconds ---" % (time.time() - start_time))

if __name__ == '__main__':
    main()
